config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    root 'application#index'
    resources :users, only: [:index]
    resources :categories, only: [:index, :new, :create, :edit, :update, :destroy]
  end

  devise_for :users

  resources :users, only: [:show]
  resources :categories, only: [:show]
  root 'home#index'

  resources :surveys do
    resources :participations, only: [:create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
	validates :name, presence: true, length: {minimum: 5}
	validates_uniqueness_of :name
	
	has_many :surveys
end

app/models/participation.rb
class Participation < ApplicationRecord
  belongs_to :participant, class_name: "User", foreign_key: "user_id"
  belongs_to :participated_survey, class_name: "Survey", foreign_key: "survey_id"
end

app/models/survey.rb
class Survey < ApplicationRecord

	enum :status, { draft: 0, invited: 10, active: 20, terminated: 30, completed: 40}
	searchkick
	belongs_to :organizer, class_name: "User", foreign_key: "user_id"
	belongs_to :category
	has_many :participations, dependent: :destroy
	has_many :participants, through: :participations

	validates :survey_name, presence: true, length: {minimum: 5}, uniqueness: true
	validates :location, presence: true

	mount_uploader :image, ImageUploader

end

app/models/user.rb
class User < ApplicationRecord
  has_many :organized_surveys, class_name: "Survey", dependent: :destroy 
  has_many :participations
  has_many :participated_surveys, through: :participations
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         def to_s
          "#{username}"
         end

         def full_name
          "#{first_name} #{last_name}"           
         end
end

app/controllers/admin/application_controller.rb
class Admin::ApplicationController < ApplicationController
  before_action :authorize_admin!
  skip_after_action :verify_authorized

  def index
    @users = User.all
    @surveys = Survey.all
    @categories = Category.all
  end

  private

  def authorize_admin!
    authenticate_user!

    unless current_user.admin?
      redirect_to root_path, alert: "You must be an admin to do that"
    end
  end
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::ApplicationController

	before_action :set_category, only: [:edit, :update, :destroy]

	def index
		@categories = Category.order(:name)
	end

	def new
		@category = Category.new
	end

	def create
		@category = Category.new(category_params)

		if @category.save
			flash[:notice] = "Category has been created"
			redirect_to admin_categories_path
		else
			flash.now[:alert] = "Category has not been created"
			render "new"
		end
	end

	def edit

	end

	def update
		if @category.update(category_params)
			flash[:notice] = "Category has been updated."
			redirect_to admin_categories_path
		else
			flash.now[:alert] = "Category has not been updpated."
			render "edit"
		end
	end

	def destroy
		@category.destroy

		flash[:alert] = "Category has been deleted."
		redirect_to admin_categories_path
	end

	private

		def category_params
			params.require(:category).permit(:name, :summary)
		end

		def set_category
			@category = Category.find(params[:id])
		end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::ApplicationController

	def index
		@users = User.order(:email)
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	before_action :configure_permitted_parameters, if: :devise_controller?

	include Pundit
	
	after_action :verify_authorized, unless: :devise_controller?

	rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

	private
		def configure_permitted_parameters
			devise_parameter_sanitizer.permit(:sign_up) do |user|
				user.permit(:email, :password, :password_confirmation, :first_name, :last_name, :username)
			end			

			devise_parameter_sanitizer.permit(:account_update) do |user|
				user.permit(:email, :password, :password_confirmation, :current_password, :first_name, :last_name, :username)
			end			

		end

		def user_not_authorized
			flash[:alert] = "You are not authorized to perform that function"
			redirect_to(request.referrer || root_path)
			
		end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

	before_action :set_category, only: [:show]
	skip_after_action :verify_authorized

	def show
		@categories = Category.order(:name)
		@category_surveys = @category.surveys.order(created_at: :desc)
	end

	private

		def set_category
			@category = Category.find(params[:id])

		rescue ActiveRecord::RecordNotFound
			flash[:alert] = "The category you just requested does not exist"
			redirect_to(request.referrer || surveys_url)
		end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	skip_after_action :verify_authorized
	
	def index
		
	end
end

app/controllers/participations_controller.rb
class ParticipationsController < ApplicationController

	before_action :set_survey
	before_action :authenticate_user!
	skip_after_action :verify_authorized

	def create
		@participation = @survey.participations.where(participant: current_user).first_or_create

		if @participation.save
			flash[:notice] = "You have selected this survey to start"
			redirect_to user_path(current_user)
		end
	end

	private

	def set_survey
		@survey = Survey.find(params[:survey_id])
	end
end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
	before_action :set_survey, only: [:show, :edit, :update, :destroy]
	before_action :authenticate_user!, except: [:index, :show]
	# before_action :authorize_owner!, only: [:edit, :update, :destroy]

	def index
		if params[:query].present?
			@surveys = Survey.search(params[:query]).page params[:page]
		else
			@surveys = Survey.order(created_at: :desc).page params[:page]
		end

		@surveys = Survey.order(created_at: :desc)
		@categories = Category.order(:name)
		authorize @surveys, :index?
	end

	def show
		authorize @survey, :show?
	end

	def new
		@survey = Survey.new

		authorize @survey, :new?
	end

	def create
		@survey = Survey.new(survey_params)

		authorize @survey, :create?
		@survey.organizer = current_user

		if @survey.save
			flash[:notice] = "Survey created!"
			redirect_to @survey
		else
			flash.now[:alert] = "Survey not created"
			render :new, status: :unprocessable_entity
		end
	end

	def edit
		authorize @survey, :edit?
	end

	def update
		authorize @survey, :update?
		if @survey.update(survey_params)
			redirect_to @survey
		else
			render :edit, status: :unprocessable_entity
		end
	end

	def destroy
		@survey.destroy
		flash[:alert] = "Survey deleted successfully"
		redirect_to surveys_path
	end


	private 

		def set_survey
			@survey = Survey.find(params[:id])

			rescue ActiveRecord::RecordNotFound
			flash.alert = "The page you requested does not exist"
			redirect_to surveys_path
		end

		def survey_params
			params.require(:survey).permit(:survey_name, :description, :start_date, :end_date, :location, :image, :cpi, :incidence, :loi, :category_id, :completes_needed, :completes_achieved)
		end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :set_user, only: [:show]
	skip_after_action :verify_authorized

	

	def show		
	end

	private

		def set_user
			@user = User.find(params[:id])		
		end
end

app/helpers/admin/application_helper.rb
module Admin::ApplicationHelper
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
	def full_title(page_title = " ")
		default_title = "Clout Cloud"
		if page_title.empty?
			default_title
		else
			"#{page_title} | #{default_title}"
		end
	end

	def time_format(event_date)
		event_date.strftime("%A, %d %b %Y %l:%M %p")
	end

	def survey_status(survey)
		if survey.end_date <= Date.today
			content_tag(:span, "", class: "past")
		else
			content_tag(:span, "", class: "upcoming")
		end		
	end

	def admins_only(&block)
		block.call if current_user.try(:admin?)		
	end

	def avatar_url(user)
		hash = Digest::MD5.hexdigest(user.email.downcase)
		"https://www.gravatar.com/avatar/#{hash}"
	end
	
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/participations_helper.rb
module ParticipationsHelper
end

app/helpers/surveys_helper.rb
module SurveysHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/application/index.html.erb
<div class="row">
	<div class="col-sm-3 admin">
		<div class="admin-sidebar">
			<div class="user-panel">
				<div class="pull-left image">
					<%= image_tag avatar_url(current_user), width: 20, class: "img-circle" %>
				</div>
				<div class="pull-left info">
					<p><%= current_user.full_name %></p>
				</div>
			</div>
		</div>
		<ul class="admin-menu">
			<li class="text-uppercase text-center header">Main Navigation</li>
			<li>
				<%= link_to admin_users_path do %>
				<%= fa_icon "users" %>
					<span>Users</span>
					<span class="label label-primary pull-right"><%= @users.count %></span>
				<% end %>
			</li>
			<li>
				<%= link_to admin_categories_path do %>
				<%= fa_icon "th" %>
					<span>Categories</span>
					<span class="label label-info pull-right"><%= @categories.count %></span>
				<% end %>
			</li>
			<li>
				<%= link_to "#" do %>
				<%= fa_icon "respondent" %>
					<span>Respondents</span>
					<span class="label label-danger pull-right">respondents</span>
				<% end %>
			</li>
			<li>
				<%= link_to surveys_path do %>
				<%= fa_icon "calendar" %>
					<span>Surveys</span>
					<span class="label label-warning pull-right"><%= @surveys.count %></span>
				<% end %>
			</li>
			<li>
				<%= link_to "#" do %>
				<%= fa_icon "tags" %>
					<span>Tags</span>
					<span class="label label-default pull-right">tags</span>
				<% end %>
			</li>
			<li>
				<%= link_to "#" do %>
				<%= fa_icon "comments" %>
					<span>Comments</span>
					<span class="label label-primary pull-right">comments</span>
				<% end %>
			</li>
			<li>
				<%= link_to "#" do %>
				<%= fa_icon "heart" %>
					<span>Likes</span>
					<span class="label label-danger pull-right">likes</span>
				<% end %>
			</li>
		</ul>
	</div>

	<div class="col-sm-9">
		<header>
			<h1>Dashboard <small>Control Panel</small></h1>
		</header>

		<h4>Welcome to Admin Dashboard</h4>
	</div>
</div>

app/views/admin/categories/_form.html.erb
<div class="row">
	<div class="col-sm-8 col-sm-offset-2">

		<%= simple_form_for([:admin, category]) do |f| %>
			<%= f.input :name %>
			<%= f.input :summary %>
			<%= f.button :submit, class: "btn btn-primary" %>
		<% end %>
	</div>
</div>

app/views/admin/categories/edit.html.erb
<header>
	<h1>Edit Category <small>(<%= @category.name %>)</small></h1>

	<%= render "form", category: @category %>
</header>

app/views/admin/categories/index.html.erb
<header>
	<h1>Categories</h1>

	<% admins_only do %>
		<ul class="actions">
			<li><%= link_to "New Category", new_admin_category_path, class: "new" %></li>
		</ul>
	<% end %>
</header>

<table class="table table-striped table-responsive">
	<thead>
		<tr>
			<th>Name</th>
			<th>Created</th>
			<th>Surveys</th>
			<th colspan="3"></th>
		</tr>
	</thead>

	<tbody>
		<% @categories.each do |category| %>
			<tr>
				<td><%= category.name %></td>
				<td><%= time_format(category.created_at) %></td>
				<td><%= "Surveys" %></td>
				<td>
					<%= link_to "View", category_path(category) %> | <%= link_to "Edit", edit_admin_category_path(category) %> | <%= link_to "Delete", admin_category_path(category), data: {turbo: false, method: :delete, confirm: 'Are you sure?'} %>
				</td>
			</tr>
		<% end %>
	</tbody>
	
</table>

app/views/admin/categories/new.html.erb
<header>
	<h1>New Category</h1>
</header>

<%= render "form", category: @category %>

app/views/admin/users/index.html.erb
<header>
	<h1>Users</h1>
</header>

<table class="table table-striped table-responsive">
	<thead>
		<tr>
			<th>User Id</th>
			<th>Avatar</th>
			<th>Username</th>
			<th>Email</th>
			<th>Joined</th>
			<th>Surveys</th>
		</tr>
	</thead>

	<tbody>
		<% @users.each do |user| %>
		<tr>
			<td><%= user.id %>
			<td><%= "Avatar" %></td>
			<td><%= user.username %></td>
			<td><%= user.email %></td>
			<td><%= time_format(user.created_at) %></td>
			<td><%= link_to user.organized_surveys.count, user_path(user) %></td>
		</tr>
		<% end %>
	</tbody>
</table>

<p><%= link_to "Back to Dashboard", admin_root_path %></p>

app/views/categories/show.html.erb
<%= provide(:title, @category.name) %>

<header>
	<h1 class="text-uppercase"><%= @category.name %> <small>Surveys</small></h1>

	<ul class="actions">
		<% admins_only do  %>
			<li><%= link_to "Edit Category", edit_admin_category_path(@category), class: "edit" %></li>

			<li><%= link_to "Delete Category", admin_category_path(@category), method: :delete, data: {confirm: "Are you sure you want to delete this category"}, class: "delete" %></li>
		<% end %>
	</ul>
</header>

<div class="row">
	<div class="col-sm-3 pull-right">
		<div class="sidebar">
			<h3 class="discover">Discover</h3>
			<ul class="nav nav-pills nav-stacked">
				<li class="<%= "active" if current_page?("/surveys")%>"><%= link_to "All Surveys", surveys_path %></li>
				<% @categories.each do |category| %>
					<li class="<%= "active" if current_page?("/categories/#{category.id}") %>">
						<%= link_to category.name, category_path(category) %>
					</li>
				<% end %>
			</ul>
		</div>
	</div>

<div class="search">
	<div class="col-sm-9">
		<h4>Discover your surveys</h4>
		<%= form_tag surveys_path, class: "form-horizontal", method: :get do  %>
			<div class="form group form-group lg">
				<div class="col-sm-10">
					<%= text_field_tag :query, params[:query], placeholder: "Search surveys here", autofocus: :true, class: "form-control" %>
				</div>
				<div class="class="col-sm-2>
					<%= submit_tag "Find", class: "btn btn-default btn-lg" %>
					<% if params[:query].present? %>
						<%= link_to "Clear", surveys_path %>
					<% end %>
				</div>
			</div>
		<% end %>
	</div>
</div>
<% @category_surveys.each do |survey| %>
		<div class="col-sm-9 pull-left">
			<%= link_to survey_path(survey) do %>
				<div class="surveys">
					<div class="row">
						<div class="col-sm-3">
							<%= image_tag "https://picsum.photos/200/100", class: "survey-image" %>
						</div>
						<div class="col-sm-9">
							<h3 class="survey-name"><%= survey.survey_name %></h3>
							<p>
								<span class="survey-location"><%= survey.location %> - <strong><%= survey.location %></strong></span>
							</p>
							<p class="lead-time">
								<span class="survey-start"><%= time_format(survey.start_date) %></span>
								<span class="pull-right">Organized by: <%= survey.organizer %></span>
							</p>
						</div>
					</div>
				</div>
			<% end %>
	</div>
<% end %>
</div>

app/views/surveys/_form.html.erb
<div class="row">
	<div class="col-sm-8 col-sm-offset-2">

		<%= simple_form_for(survey) do |f| %>

			<%= f.input :survey_name %>

			<%= f.input :description %>

			<%= f.input :start_date, as: :date, start_year: Date.today.year, ampm: true, order: [:month, :day, :year] %>

			<%= f.input :end_date, as: :date, start_year: Date.today.year, ampm: true, order: [:month, :day, :year] %>

			<%= f.input :location %>

			<%= f.input :category_id, collection: Category.all, label: "Select Category", prompt: true %>

			<%= f.input :cpi %>

			<%= f.input :incidence %>

			<%= f.input :loi %>

			<%= f.input :completes_needed %>

			<%= f.input :image, as: :file, label: "Upload Survey Image" %>

			<%= f.button :submit, class: "btn btn-primary" %>

		<% end %>
		<p><%= link_to "Back", surveys_path %>
	</div>
</div>

app/views/surveys/edit.html.erb
<header>
	<h1>Edit Survey</h1>
</header>
<%= render "form", survey: @survey %>

app/views/surveys/index.html.erb
<header>
	<h1>All Surveys</h1>
	<ul class="actions">
		<li><%= link_to "New Survey", new_survey_path, class: "new" if policy(Survey).new? %></li>
	</ul>
</header>

<div class="row">
	<div class="col-sm-3 pull-right">
		<div class="sidebar">
			<h3 class="discover">Discover</h3>
			<ul class="nav nav-pills nav-stacked">
				<li class="<%= "active" if current_page?("/surveys")%>"><%= link_to "All Surveys", surveys_path %></li>
								<% @categories.each do |category| %>
					<li class="<%= "active" if current_page?("/categories/#{category.id}") %>">
						<%= link_to category.name, category_path(category) %>
					</li>
				<% end %>

			</ul>
		</div>
	</div>

<div class="search">
	<div class="col-sm-9">
		<h4>Discover your surveys</h4>
		<%= form_tag surveys_path, class: "form-horizontal", method: :get do  %>
			<div class="form group form-group lg">
				<div class="col-sm-10">
					<%= text_field_tag :query, params[:query], placeholder: "Search surveys here", autofocus: :true, class: "form-control" %>
				</div>
				<div class="class="col-sm-2>
					<%= submit_tag "Find", class: "btn btn-default btn-lg" %>
					<% if params[:query].present? %>
						<%= link_to "Clear", surveys_path %>
					<% end %>
				</div>
			</div>
		<% end %>
	</div>
</div>
<% @surveys.each do |survey| %>
		<div class="col-sm-9 pull-left">
			<%= link_to survey_path(survey) do %>
				<div class="surveys">
					<div class="row">
						<div class="col-sm-3">
							<%= image_tag "https://picsum.photos/200/100", class: "survey-image" %>
						</div>
						<div class="col-sm-9">
							<h3 class="survey-name"><%= survey.survey_name %></h3>
							<p>
								<span class="survey-reward"><strong>Survey Reward: </strong><%= number_to_currency(survey.cpi) %></span>
							</p>
							<p>
								<span class="survey-category"><strong>Survey Category: </strong><%= survey.category.name %></span>
							</p>
							<p>
								<span class="survey-completes"><strong>Completes Needed: </strong><%= survey.completes_needed %></span>
							</p>
							<p class="lead-time">
								<span class="survey-start"><%= time_format(survey.start_date) %></span>
								<span class="pull-right">Survey Status: <%= survey.status.humanize %></span>
							</p>
						</div>
					</div>
				</div>
			<% end %>
	</div>
<% end %>	

<div class="text-center">

<!-- Error with paginating pages -->
 <!-- paginate @surveys -->
</div>

</div>

app/views/surveys/new.html.erb
<header>
	<h1>New Survey</h1>	
</header>

<%= render "form", survey: @survey %>

app/views/surveys/show.html.erb
<% provide(:title, @survey.survey_name) %>

<header>
	<h1 id="show-survey"><%= @survey.survey_name %></h1>
	<ul class="actions">
		<li><%= link_to "Edit Survey", edit_survey_path(@survey), class: "edit" if policy(@survey).edit? %></li>
		<li><%= link_to "Delete Survey", @survey, method: :delete, data: {confirm: "Are you sure?"}, class: "delete" if policy(@survey).destroy? %></li>
		<li><%= link_to "Take Survey", survey_participations_path(@survey), method: :post, class: "new" %></li>
	</ul>
</header>

<div class="row">
	<div class="col-sm-9">
		<!-- <%= image_tag "https://picsum.photos/350/200", class: "survey-image" %> -->

		<div class="survey-details">
			<h4><span class="survey-start"><strong>Starts:</strong> <%= time_format(@survey.start_date) %></span></h4>
			<p>
				<span class="survey-end"><strong>Ends:</strong> <%= time_format(@survey.end_date) %></span>
			</p>
		</div>
		<div class="survey-details">
			<h3>Survey Details</h3>
			<p><span class="survey-details"><strong>Survey Category:</strong> <%= @survey.category.name %> </span></p>
			<p><span class="survey-details"><strong>Survey Description:</strong> <%= @survey.description %> </span></p>
			<p><span class="survey-details"><strong>Cost Per Interview:</strong> <%= number_to_currency(@survey.cpi) %></span></p>
			<p><span class="survey-details"><strong>Survey Incidence Rate:</strong> <%= @survey.incidence %></span></p>
			<p><span class="survey-details"><strong>Length of Interview:</strong> <%= @survey.loi %></span></p>
			<p><span class="survey-details"><strong>Completes Needed:</strong> <%= @survey.completes_needed %></span></p>
			<p><span class="survey-details"><strong>Survey Status:</strong> <%= @survey.status.humanize %></span></p>
		</div>
	</div>

	<div class="col-sm-3">
		<div class="sidebar">
			<h4 class= "organizer"><%= link_to @survey.organizer.username, user_path(@survey.organizer) %></h4>
			<p>
				<span class="survey-location">Survey Location: <strong><%= @survey.location %></strong></span>
			</p>
		</div>
		<div class="sidebar">
			<h4 class="survey-venue">Respondents</h4>
		</div>
		
	</div>
</div>

app/views/users/show.html.erb
<header>
	<h1><%= @user.first_name %>'s Surveys Created</h1>

	<ul class="actions">
		<li><%= link_to "Start Survey", new_survey_path, class: "new" if policy(Survey).new?%></li>
	</ul>
</header>

<!-- This is for organized events -->

<% if @user.organized_surveys.any? %>
	<table class="table table-striped">
		<thead>
			<tr>
				<th>Survey</th>
				<th>Start Date</th>
				<th>End Date</th>
				<th>Survey Status</th>
				<th colspan="3"></th>
			</tr>
		</thead>

		<tbody>
			<% @user.organized_surveys.reverse.each do |survey| %>
				<tr>
					<td><%= link_to survey.survey_name, survey_path(survey) %></td>
					<td><%= time_format(survey.start_date) %></td>
					<td><%= time_format(survey.end_date) %></td>
					<td><%= time_format(survey.start_date) %></td>
					<td><%= survey_status(survey) %></td>

					<td>
						<%= link_to "Edit", edit_survey_path(survey), class: "edit" if policy(survey).edit? %>
						<%= link_to "Delete", survey_path(survey), method: :delete, data: {confirm: "Are you sure?"}, class: "delete" if policy(survey).destroy? %>
					</td>

				</tr>
			<% end %>
		</tbody>
	</table>
	<% else %>
	<p><%= @user.organization_name %> has no surveys yet</p>
<% end %>

<!-- This is for participated in surveys -->

<header>
	<h1><%= @user.first_name %>'s Surveys Started</h1>
</header>

<% if @user.participated_surveys.any? %>
	<table class="table table-striped">
		<thead>
			<tr>
				<th>Survey</th>
				<th>Start Date</th>
				<th>End Date</th>
				<th>Survey Status</th>
				<th colspan="3"></th>
			</tr>
		</thead>

		<tbody>
			<% @user.participated_surveys.reverse.each do |survey| %>
				<tr>
					<td><%= link_to survey.survey_name, survey_path(survey) %></td>
					<td><%= time_format(survey.start_date) %></td>
					<td><%= time_format(survey.end_date) %></td>
					<td><%= time_format(survey.start_date) %></td>
					<td><%= survey_status(survey) %></td>

					<td>
						<%= link_to "Edit", edit_survey_path(survey), class: "edit" if policy(survey).edit? %>
						<%= link_to "Delete", survey_path(survey), method: :delete, data: {confirm: "Are you sure?"}, class: "delete" if policy(survey).destroy? %>
					</td>

				</tr>
			<% end %>
		</tbody>
	</table>
	<% else %>
	<p><%= @user.organization_name %> has not participated in any surveys yet</p>
<% end %>